parentItem = {
  nlloc: '4',
  nlsub: '1',
  _button: '',
  nsapiFC: '',
  wfVF: '',
  nlapiVF: '',
  externalid: '',
  nlapiRC: '',
  _eml_nkey_: '4537321_SB1~1322963~1014~N',
  nlapiVI: '',
  type: 'suitescriptform',
  nlapiVD: '',
  deploy: '1',
  nsapiRC: '',
  customwhence: '',
  nsapiVF: '',
  nsapiVD: '',
  nlapiVL: '',
  nsbrowserenv: 'istop=T',
  id: '',
  nsapiVL: '',
  nlapiFC: '',
  nsapiVI: '',
  custpage_brand: '',
  wfPS: '',
  entryformquerystring: '',
  script: '759',
  submitted: 'T',
  _multibtnstate_: '',
  selectedtab: '',
  wfPI: '',
  nlapiSR: '',
  submitter: 'Get Parents',
  wfinstances: '',
  nsapiLI: '',
  custpage_category: '',
  inpt_custpage_category: ' ',
  nsapiPS: '',
  nsapiCT: '1636381488688',
  nlapiPI: '',
  nluser: '1322963',
  nldept: '0',
  nsapiPI: '',
  clickedback: '',
  wfSR: '',
  nsapiLC: '',
  nlapiPS: '',
  custpage_brand_display: '<Type then tab>',
  nlapiLI: '',
  nsapiPD: '',
  nsapiSR: '',
  custpage_parent_item_display: 'AXLE LT NEW BKP',
  whence: '/app/common/scripting/scriptrecord.nl?id=1047',
  nlrole: '3',
  custpage_parent_item: '1584320',
  _csrf:
    'sn0Cj4BiSWjBqc8HTOrq9pIDHWoPBir1v8EaKs7-EDvIHEHJ-a3NhDGYLOdJ1EUsLtC8v-WInXv62M-pneFEW8w6lhWF6GtYLDEG2jPofYjfAEkC2gEIa1ejTi2vForPAfY-zYm6WT0gemCQ7wiFksN7sMeVii3UxPQotCGoeAU=',
  formdisplayview: 'DETAIL_VIEW',
  wfFC: ''
}
