var itemRec = {
  id: '40018',
  type: 'inventoryitem',
  isDynamic: false,
  fields: {
    costingmethoddisplay: 'Average',
    custpage_ava_taxcodemapping: 'PC040400',
    autoleadtime: 'T',
    custitem_kit_is_best_seller: 'F',
    custitem_wms_imgurl:
      'https://imgs.2ndswing.com/images/clean-product/small/08 BURNER RESCUE HYG.jpg',
    custitem_g2_liston2sonly: 'F',
    _eml_nkey_: '4537321_SB1~1322963~1038~N',
    type: 'item',
    custitem_has_used_inventory: 'T',
    custitem_g2_itemtype_ref: '1',
    pricingchange: 'F',
    cogsaccount: '124',
    custitem_g2_model_ref: '3802',
    id: '40018',
    custitem_g2_hasimage: 'T',
    custitem_g2_priceprotected: 'F',
    costestimatetype: 'AVGCOST',
    custitem_master_opportunity_sku: 'F',
    entryformquerystring: 'itemtype=InvtPart&e=T&id=40018',
    custitem_bid_price_copy: '10.00',
    version: '47',
    custitem_msrp_copy: '179.99',
    isdonationitem: 'F',
    custitem_eol_notsenttomb: 'F',
    custitem_g2_showbuybutton: 'F',
    nextagproductfeed: 'F',
    shopzillaproductfeed: 'F',
    custitem_g2_opportunitybuy: 'F',
    custitem_g2_ironsetclubs_refs: '',
    createddate: '1/21/2019 1:58 pm',
    custitem_associated_headcover_refs: '',
    froogleproductfeed: 'F',
    custitem_g2_tourissue: 'F',
    incomeaccount: '54',
    supplyreplenishmentmethod: 'REORDER_POINT',
    custitem_red_flag_fit_list: 'F',
    itemidorig: '08 BURNER RESCUE HYG',
    nluser: '1322963',
    custitem_fit_list: 'F',
    custitem_g2_default_shaft_model_refs: '',
    custitem_base_price_copy: '29.99',
    custitem_g2_club_desiredballflight_ref: '5',
    custitem_multi_conv_from: '',
    origbinactive: 'F',
    custitem_wms_receivingshell: 'F',
    custitem_g2_hasnewitems: 'F',
    usebins: 'F',
    enforceminqtyinternally: 'T',
    seasonaldemand: 'F',
    custitem_g2_ironsetdefaultclubs_refs: '',
    custitem_g2_summary:
      "The TaylorMade 2008 Burner Rescue Hybrid features a larger, triangular head with TaylorMade's SuperFast Technology for any player looking for maximum distance from any lie.The fast looking triangular head shape allows this hybrid to have an ultra low, ultra deep CG location, making it easier to launch and more forgiving from any lie. TaylorMade's SuperFast technology gives the '08 Burner Rescue an exceptionally low total club weight, promoting faster swing speed and leading to more distance. Buy the TaylorMade 2008 Burner Rescue Hybrid at 2nd Swing today and get a great deal when you trade in your current clubs!",
    custpage_ava_readconfig:
      '{"custrecord_ava_disabletaxsalesorder":false,"custrecord_ava_adduppercase":false,"custrecord_ava_enableusetax":false,"custrecord_ava_password":"335bab6dbfbe5f1ab7e0d85dc6ad7e7c","custrecord_ava_enablevatin":false,"custrecord_ava_entityusecode":true,"custrecord_ava_enablelogentries":1,"custrecord_ava_abortworkflowscripts":false,"custrecord_ava_compid":"837629","custrecord_ava_accountvalue":"2000318757","custrecord_ava_enablediscount":false,"custrecord_ava_encryptflag":true,"custrecord_ava_deftaxcode":"AVATAX+1156125","scriptid":"val_22114133_4537321_530","custrecord_ava_defcompanycode":"GOLFSTIX","custrecord_ava_disableloccode":false,"id":"1","custrecord_ava_configflag":true,"custrecord_ava_state":"MN","custrecord_ava_abortsuitelets":false,"custrecord_ava_enableupccode":false,"custrecord_ava_servicetypes":"TaxSvc, AddressSvc, AvaCert2Svc","custrecord_ava_decimalplaces":2,"custrecord_ava_taxrate":0,"custrecord_ava_abortscheduledscripts":false,"custrecord_ava_username":"cflaherty@2ndswing.com","custrecord_ava_abortuserinterfaces":false,"custrecord_ava_disableline":true,"custrecord_ava_vendorcode":"2","custrecord_ava_defaultcustomer":1,"custrecord_ava_defshipcode":"FR020100","custrecord_ava_licensekey":"e2065bf820b2c7026c2ba62f9f4e5902627cda694e675413eb8e28c1913da9dd","custrecord_ava_address1":"6752 Shady Oak Rd","custrecord_ava_autoassessbill":false,"custrecord_ava_itemaccount":false,"custrecord_ava_zip":"55344-3427","custrecord_ava_customercode":"2","custrecord_ava_taxinclude":false,"isinactive":false,"custrecord_ava_enableaddvalontran":true,"custrecord_ava_billapproved":false,"custrecord_ava_discountmapping":0,"custrecord_ava_enablelogging":true,"custrecord_ava_addressee":"2nd Swing","custrecord_ava_country":"US","custrecord_ava_url":"1","custrecord_ava_taxondemand":true,"custrecord_ava_city":"Eden Prairie","custrecord_ava_abortbulkbilling":false,"recordtype":"customrecord_avaconfig","custrecord_ava_disabletax":false,"custrecord_ava_udf2":false,"custrecord_ava_abortcsvimports":false,"custrecord_ava_taxcodepreced":false,"custrecord_ava_udf1":false,"custrecord_ava_showmessages":3,"custrecord_ava_enableaddvalflag":false,"custrecord_ava_abortwebservices":false,"custrecord_ava_discounttaxcode":"NT","custrecord_ava_disabletaxquotes":false,"custrecord_ava_taxcodemapping":true,"custrecord_ava_addbatchprocessing":"1","custrecord_ava_disableaddvalidation":true,"custrecord_ava_markcusttaxable":1,"recordid":1,"custrecord_ava_billtimename":"0","custrecord_ava_useinvoiceaddress":false,"custrecord_ava_usepostingdate":false}',
    showdefaultdonationamount: 'F',
    custitem_displ_in_parent_modified: 'T',
    custitem_g2_shaft_gripped: 'F',
    custitem_g2_endoflife: 'T',
    custitem_g2_category_ref: '9',
    custitem_g2_okforeb: 'F',
    shipindividually: 'F',
    customform: '30',
    isdropshipitem: 'F',
    custitem_setting_used_parent_first_tim: 'F',
    custitem_wms_override_titles: 'F',
    custitem_g2_name: 'TaylorMade 2008 Burner Rescue Hybrid',
    custitem_wms_genericconversionitem: 'F',
    custitem_exempt_from_price_change: 'F',
    custitem_needs_new_label: 'F',
    nlloc: '4',
    nlsub: '1',
    binmapchange: 'F',
    shoppingproductfeed: 'F',
    custitem_ignore_reprint_logic: 'F',
    externalid: '08 BURNER RESCUE HYG',
    custitem_g2_video_refs: '94',
    custitem_image_uploader_called: 'F',
    itemtypename: 'Inventory Item',
    isonline: 'F',
    pricematrixfields: 'price',
    autoreorderpoint: 'T',
    pricequantity1: '0',
    accchange: 'F',
    custitem_g2_okforaz: 'F',
    custitem_g2_techconstruction:
      '<table class="tftable" border="1">\r\n<tr><th>Club</th><th>Loft</th><th>Length</th><th>Lie</th><th>SW</th></tr>\r\n<tr><td>T2</td><td>18°</td><td>39.5"</td><td>60°</td><td>D3</td></tr>\r\n<tr><td>T3</td><td>20°</td><td>39"</td><td>60.5°</td><td>D3</td></tr>\r\n<tr><td>T4</td><td>23°</td><td>38.5"</td><td>61°</td><td>D3</td></tr>\r\n<tr><td>2</td><td>17°</td><td>40"</td><td>60°</td><td>D3</td></tr>\r\n<tr><td>3</td><td>19°</td><td>39.5"</td><td>60.5°</td><td>D3</td></tr>\r\n<tr><td>4</td><td>22°</td><td>39"</td><td>61°</td><td>D3</td></tr>\r\n<tr><td>5</td><td>25°</td><td>38.5"</td><td>61.5°</td><td>D3</td></tr>\r\n<tr><td>6</td><td>28°</td><td>38"</td><td>62°</td><td>D3</td></tr>\r\n</table>',
    custitem_club_is_bonded: 'F',
    custitem_g2_iscalltoorder: 'F',
    salesdescription:
      "The TaylorMade 2008 Burner Rescue Hybrid features a larger, triangular head with TaylorMade's SuperFast Technology for any player looking for maximum distance from any lie.The fast looking triangular head shape allows this hybrid to have an ultra low, ultra deep CG location, making it easier to launch and more forgiving from any lie. TaylorMade's SuperFast technology gives the '08 Burner Rescue an exceptionally low total club weight, promoting faster swing speed and leading to more distance. Buy the TaylorMade 2008 Burner Rescue Hybrid at 2nd Swing today and get a great deal when you trade in your current clubs!",
    custitem_kit_needs_refresh: 'F',
    custitem_maybe_needs_new_label: 'F',
    custitem_g2_brand_ref: '133',
    custitem_g2_sku: '08 BURNER RESCUE HYG',
    custpage_url_text:
      '/app/site/hosting/scriptlet.nl?script=265&deploy=1&compid=4537321_SB1',
    custpage_ava_itemmapid: '2305729',
    custitem_parent_item_lookup_display: 'F',
    custitem_g2_hasuseditems: 'F',
    origexchangerate: '1.00',
    custitem6: 'F',
    custitem2: '',
    internalid: '40018',
    custitem_g2_gm_dvr: '11',
    custitem4: '',
    priceheadercount: '5',
    custitem1: '',
    storedescription: 'TaylorMade 2008 Burner Rescue Hybrid Graphite',
    custitem_g2_okforsf: 'T',
    matchbilltoreceipt: 'F',
    usemarginalrates: 'F',
    modifiableitemid: '08 BURNER RESCUE HYG',
    isinactive: 'F',
    istaxable: 'F',
    wfinstances: '',
    custitem_ava_taxcode: 'PC040400',
    dontshowprice: 'F',
    atpmethod: 'CUMULATIVE_ATP_WITH_LOOK_AHEAD',
    nsapiCT: '1646329784899',
    itemid: '08 BURNER RESCUE HYG',
    sys_id: '4865825778150420',
    custitem_customization_used_ref: '9732366',
    offersupport: 'F',
    nldept: '0',
    assetaccount: '144',
    custitem_bypass_60_day_hold_etail: 'F',
    custitem_multi_sku_created: 'F',
    custitem_is_bad_parent: 'F',
    custitem_wms_isverified: 'F',
    custitem_wipfli_isecommercesnap: '',
    copydescription: 'F',
    templatestored: 'F',
    excludefromsitemap: 'F',
    priceheader: 'pricequantity',
    custitem_refresh_used_skus: 'F',
    autopreferredstocklevel: 'T',
    costingmethod: 'AVG',
    custitem_g2_rareunique: 'F',
    lastmodifieddate: '12/22/2021 3:54 pm',
    custitem_g2_yearrelease: '2008',
    custitem_g2_hidepriceuntilcart: 'F',
    nlrole: '3',
    yahooproductfeed: 'F',
    _csrf:
      'Rrqwt5K9PP-FlC7Q0eKjSX9xvp7IVqnYSdkYTHQtzlh-e6sGHPe37jL9X_IFOqWeiOCE6oJy_MGIUAgDPJvIBUftsXgtcJ9f4sWn6AWKw74du1Rx6AR1lGoUjEbFWLN7NHcDh-WDzO0WF3D4yewrYaDHJnkBOmSwa-DMs-mpd9o=',
    custitem_g2_isecommerceitem: 'F',
    isgcocompliant: 'F',
    custitem_ok_mint95: 'F',
    baserecordtype: 'inventoryitem',
    custpage_ava_servicetypes: 'TaxSvc, AddressSvc, AvaCert2Svc',
    keywordschange: 'F',
    custpage_ava_udf2: '',
    hasparent: 'F',
    custpage_ava_udf1: '',
    itemtype: 'InvtPart',
    billpricevarianceacct: '58',
    custitem_wipfli_itemhasimagesnap: '',
    custitem_show_model_on_2s: 'F',
    originalusebins: 'F',
    custitem_g2_isclassicsku: 'F',
    custitem_g2_okforstores: 'T',
    isspecialorderitem: 'F',
    haschildren: 'T',
    vendormapchange: 'F'
  },
  sublists: {
    sitecategory: {
      currentline: {
        category: '',
        categorydescription: '',
        isdefault: '',
        sys_id: '-4865828559288819',
        sys_parentid: '4865825778150420',
        website: '',
        '#': '1'
      }
    },
    quantitypricinglevel: {},
    binnumber: {
      currentline: {
        binnumber: '',
        isold: '',
        location: '',
        locationactive: '',
        onhand: '',
        onhandavail: '',
        preferredbin: '',
        sys_id: '-4865828559239740',
        sys_parentid: '4865825778150420',
        '#': '1'
      }
    },
    price: {
      'line 1': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': '29.99',
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '1',
        pricelevelname: 'Base Price',
        sys_id: '4865825778345267',
        sys_parentid: '4865825778150420'
      },
      'line 2': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': null,
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '2',
        pricelevelname: 'Alternate Price 1',
        sys_id: '4865825778335512',
        sys_parentid: '4865825778150420'
      },
      'line 3': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': null,
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '3',
        pricelevelname: 'Alternate Price 2',
        sys_id: '4865825778325930',
        sys_parentid: '4865825778150420'
      },
      'line 4': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': null,
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '4',
        pricelevelname: 'Alternate Price 3',
        sys_id: '4865825778309738',
        sys_parentid: '4865825778150420'
      },
      'line 5': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': null,
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '8',
        pricelevelname: 'Amazon Price',
        sys_id: '4865825778300086',
        sys_parentid: '4865825778150420'
      },
      'line 6': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': '10.00',
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '6',
        pricelevelname: 'Bid Price',
        sys_id: '4865825778290345',
        sys_parentid: '4865825778150420'
      },
      'line 7': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': null,
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '12',
        pricelevelname: 'Clearance Price',
        sys_id: '4865825778280442',
        sys_parentid: '4865825778150420'
      },
      'line 8': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': null,
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '215',
        pricelevelname: 'Cost',
        sys_id: '4865825778270992',
        sys_parentid: '4865825778150420'
      },
      'line 9': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': null,
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '9',
        pricelevelname: 'EBay Price',
        sys_id: '4865825778261187',
        sys_parentid: '4865825778150420'
      },
      'line 10': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': '179.99',
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '10',
        pricelevelname: 'MSRP',
        sys_id: '4865825778251711',
        sys_parentid: '4865825778150420'
      },
      'line 11': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': '29.99',
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '115',
        pricelevelname: 'Max Used Base Price',
        sys_id: '4865825778241583',
        sys_parentid: '4865825778150420'
      },
      'line 12': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': null,
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '413',
        pricelevelname: 'Max Used Out Of State Price',
        sys_id: '4865825778231506',
        sys_parentid: '4865825778150420'
      },
      'line 13': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': '23.99',
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '316',
        pricelevelname: 'Min Used Base Price',
        sys_id: '4865825778221556',
        sys_parentid: '4865825778150420'
      },
      'line 14': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': null,
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '218',
        pricelevelname: 'Min Used Out Of State Price',
        sys_id: '4865825778212065',
        sys_parentid: '4865825778150420'
      },
      'line 15': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': null,
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '11',
        pricelevelname: 'Out Of State Price',
        sys_id: '4865825778202254',
        sys_parentid: '4865825778150420'
      },
      'line 16': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': null,
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '7',
        pricelevelname: 'Sales Rep Price',
        sys_id: '4865825778192552',
        sys_parentid: '4865825778150420'
      },
      'line 17': {
        currency: '1',
        discount: null,
        discountdisplay: null,
        'price[1]': null,
        'price[2]': null,
        'price[3]': null,
        'price[4]': null,
        'price[5]': null,
        pricelevel: '5',
        pricelevelname: 'Online Price',
        sys_id: '4865825778180119',
        sys_parentid: '4865825778150420'
      }
    },
    locations: {
      'line 1': {
        averagecostmli: null,
        configurationid: '171080',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '1',
        location_display: '01 Minneapolis',
        locationid: '1',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778710069',
        sys_parentid: '4865825778150420'
      },
      'line 2': {
        averagecostmli: null,
        configurationid: '171083',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '2',
        location_display: '02 Minnetonka',
        locationid: '2',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778691598',
        sys_parentid: '4865825778150420'
      },
      'line 3': {
        averagecostmli: null,
        configurationid: '171085',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '3',
        location_display: '03 Scottsdale (N)',
        locationid: '3',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778673983',
        sys_parentid: '4865825778150420'
      },
      'line 4': {
        averagecostmli: null,
        configurationid: '171089',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '16',
        location_display: '04 Wilmington',
        locationid: '16',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778654956',
        sys_parentid: '4865825778150420'
      },
      'line 5': {
        averagecostmli: null,
        configurationid: '11095101',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '116',
        location_display: '05 Columbia',
        locationid: '116',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778637145',
        sys_parentid: '4865825778150420'
      },
      'line 6': {
        averagecostmli: null,
        configurationid: '34603719',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '221',
        location_display: '06 Scottsdale (S)',
        locationid: '221',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778618832',
        sys_parentid: '4865825778150420'
      },
      'line 7': {
        averagecostmli: null,
        configurationid: '171091',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '14',
        location_display: '49 Ryder Cup Pop Up Store',
        locationid: '14',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778599706',
        sys_parentid: '4865825778150420'
      },
      'line 8': {
        averagecostmli: null,
        configurationid: '171093',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '5',
        location_display: '50 Minnesota Golf Show',
        locationid: '5',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778581964',
        sys_parentid: '4865825778150420'
      },
      'line 9': {
        averagecostmli: null,
        configurationid: '171095',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '6',
        location_display: '51 Online Returns',
        locationid: '6',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778563695',
        sys_parentid: '4865825778150420'
      },
      'line 10': {
        averagecostmli: null,
        configurationid: '171097',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '7',
        location_display: "52 Items Can't Be Found",
        locationid: '7',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778544439',
        sys_parentid: '4865825778150420'
      },
      'line 11': {
        averagecostmli: null,
        configurationid: '171098',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '8',
        location_display: '54 Issues Location',
        locationid: '8',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778526436',
        sys_parentid: '4865825778150420'
      },
      'line 12': {
        averagecostmli: null,
        configurationid: '171099',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '9',
        location_display: '55 Repairs/Warranties',
        locationid: '9',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778507956',
        sys_parentid: '4865825778150420'
      },
      'line 13': {
        averagecostmli: null,
        configurationid: '34111231',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '219',
        location_display: '60 Custom Drop Ship',
        locationid: '219',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778490545',
        sys_parentid: '4865825778150420'
      },
      'line 14': {
        averagecostmli: null,
        configurationid: '171100',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '10',
        location_display: '90 eBay',
        locationid: '10',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778473031',
        sys_parentid: '4865825778150420'
      },
      'line 15': {
        averagecostmli: null,
        configurationid: '171101',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '11',
        location_display: '96 2ndswing.com',
        locationid: '11',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778454913',
        sys_parentid: '4865825778150420'
      },
      'line 16': {
        averagecostmli: null,
        configurationid: '171102',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '12',
        location_display: '97 Amazon',
        locationid: '12',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778436588',
        sys_parentid: '4865825778150420'
      },
      'line 17': {
        averagecostmli: null,
        configurationid: '171103',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '4',
        location_display: '98 Eden Prairie',
        locationid: '4',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: '0',
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778418988',
        sys_parentid: '4865825778150420'
      },
      'line 18': {
        averagecostmli: null,
        configurationid: '34676038',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '321',
        location_display: '98 Eden Prairie : Eden Prairie',
        locationid: '321',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778400730',
        sys_parentid: '4865825778150420'
      },
      'line 19': {
        averagecostmli: null,
        configurationid: '171104',
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '13',
        location_display: '99 Sideline Swap',
        locationid: '13',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: '0',
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778382899',
        sys_parentid: '4865825778150420'
      },
      'line 20': {
        averagecostmli: null,
        configurationid: null,
        costaccountingstatus: null,
        defaultreturncost: null,
        invtclassification: null,
        invtcountinterval: null,
        lastinvtcountdate: null,
        lastpurchasepricekey: null,
        lastpurchasepricemli: null,
        lastpurchasepriceperm: 'NONE_NEEDED',
        lastpurchasepriceurl: '/app/accounting/transactions/transaction.nl',
        location: '322',
        location_display: 'ClubTrial Program',
        locationid: '322',
        nextinvtcountdate: null,
        onhandvaluemli: null,
        preferredstocklevel: null,
        quantityavailable: null,
        quantitybackordered: null,
        quantitycommitted: null,
        quantityintransit: null,
        quantityonhand: null,
        quantityonorder: null,
        reorderpoint: null,
        savedpreferredstocklevel: null,
        savedreorderpoint: null,
        sys_id: '4865825778362772',
        sys_parentid: '4865825778150420'
      }
    },
    presentationitem: {
      currentline: {
        baseprice: '',
        description: '',
        item: '',
        itemtype: '',
        onlineprice: '',
        presentationitem: '',
        sys_id: '-4865828559175642',
        sys_parentid: '4865825778150420',
        '#': '1'
      }
    }
  }
}
