var createMockRecord = {
  type: 'purchaseorder',
  id: '293080',
  fields: {
    _csrf:
      '8Y4xNyWFO1sOd_hgGUvzCrsSM3btJ8iAK5O5zfln7T-dAwn590CELszN5SlCIRiO_e7V7FqylKbjUTtriLN9HB0tS_5aiTe7AeihTMJ3E-X6fS-77MNRgyfmmwY9fuQzX0sVhTwX5Cu5vd7tgK_XMEEUZI-arnwvNknoNhQ3f4U=',
    _eml_nkey_: '4537321_SB1~1322963~1033~N',
    balance: '0',
    balreadyrefunded: 'F',
    baserecordtype: 'purchaseorder',
    billaddress:
      'Stonecrest Country Club\n12347 ne 52nd loop\noxford FL 34484\nUnited States',
    billaddresslist: '1446798',
    billingaddress2_set:
      "var subrecord = nlapiViewSubrecord('billingaddress');\nvar addresstext;\nif (subrecord) {\n   addresstext = subrecord.getFieldValue('addrtext');\n} else {\n}\nnlapiSetFieldValue('billingaddress_text', addresstext);\n",
    billingaddress_key: '1453217',
    billingaddress_text:
      'Stonecrest Country Club\n12347 ne 52nd loop\noxford FL 34484\nUnited States',
    billingaddress_type: 'shipaddr',
    billisresidential: 'F',
    class: '2',
    companyid: '95382',
    createddate: '5/5/2019 12:36 pm',
    creditlimit_origtotal: '907.64',
    currency: '1',
    currencyprecision: '2',
    currencysymbol: 'USD',
    custbody_alert_of_var_email: 'F',
    custbody_bf_pototalquantity: '7',
    custbody_bf_prepaidpo: 'T',
    custbody_bf_totalquantity2: '7',
    custbody_cp_ponum: 'G000614',
    custbody_emailorderreceivedsummary: 'T',
    custbody_employee_ref: '923849',
    custbody_g2_isfreeshipping: 'F',
    custbody_g2_ispayinadvance: 'F',
    custbody_g2_source: 'W',
    custbody_gsv_pocount: '0',
    custbody_gsvsite_ref: '3',
    custbody_intercompany: 'F',
    custbody_isclubtrader: 'F',
    custbody_isexcess: 'T',
    custbody_isgiftcertissued: 'F',
    custbody_paycode_ref: '1',
    custbody_pricelevel_ref: '11',
    custbody_requested_amount: '907.64',
    custbody_site_paycode_adj_pct: '1',
    custbody_site_price_adj_pct: '1',
    custbody_variance_email_sent: 'F',
    custbody_vendor_name: 'Stonecrest Country Club',
    custbody_weborderid: '2871',
    custbody_widgettype_ref: '4',
    custbody_wipfli_child_item_compl: 'F',
    custbody_wipfli_customer_email: 'sammypga2@pga.com',
    custbody_wipfli_customer_phone: '352-205-5331',
    custbody_wipfli_hot_order: 'F',
    custbody_wipfli_povariance: '-907.64',
    custbody_wipfli_shipping_address:
      '2412 East Hennepin Ave\nMinneapolis, MN 55413',
    custbody_wipfli_vend_cat: '13',
    custbody_wipfli_vendorbalance: '0.00',
    custbody_wipfli_wpc: '2',
    custbody_wms_customer_not_found: 'F',
    custbody_wms_po_total_received: '0',
    custbody_wms_prepay_invoice: '296215',
    custbody_wms_prepayment_credit_applied: 'F',
    custbody_wms_total_received_2: '0',
    customform: '116',
    dbstrantype: 'PurchOrd',
    edition: 'US',
    email: 'sammypga2@pga.com',
    entity: '95382',
    entityfieldname: 'entity',
    entityname: 'Stonecrest Country Club (G00581)',
    entryformquerystring: 'e=T&id=293080',
    exchangerate: '1',
    expense_total: '0.00',
    externalid: 'PO-G000614',
    haslines: 'T',
    id: '293080',
    initialtranid: 'PO-G000614',
    installmentcount: '0',
    inventorydetailuitype: 'MOH_LOOSE_VALIDATION',
    isbasecurrency: 'T',
    item_total: '907.64',
    lastmodifieddate: '5/16/2019 1:55 pm',
    linked: 'F',
    linkedclosedperioddiscounts: 'F',
    linkedrevrecje: 'F',
    needsbill: 'F',
    needsshiprecv: 'T',
    nexttranid: '2269',
    nlapiCC: 'F',
    nldept: '0',
    nlloc: '4',
    nlrole: '1033',
    nlsub: '1',
    nluser: '1322963',
    nsapiCT: '1620050990000',
    ntype: '15',
    oldrevenuecommitment: 'F',
    ordbilled: 'F',
    orderstatus: 'B',
    ordpartrecvd: 'F',
    ordrecvd: 'F',
    originator: 'webServices',
    origtotal: '-907.64',
    origtotal2: '907.64',
    prevdate: '4/19/2014',
    recordcreatedby: '94875',
    recordcreateddate: '05/05/2019 10:36:58',
    rectype_261_737_maxnkey: '651581',
    rejected: 'F',
    shipaddress: '6752 Shady Oak Road\nEden Prairie MN 55344\nUnited States',
    shipdate: '5/5/2019',
    shipisresidential: 'F',
    shipoverride: 'F',
    shippingaddress2_set:
      "var subrecord = nlapiViewSubrecord('shippingaddress');\nvar addresstext;\nif (subrecord) {\n   addresstext = subrecord.getFieldValue('addrtext');\n} else {\n}\nnlapiSetFieldValue('shippingaddress_text', addresstext);\n",
    shippingaddress_type: 'shipaddr',
    source: 'Web Services',
    status: 'Pending Receipt',
    statusRef: 'pendingReceipt',
    subsidiary: '1',
    supervisorapproval: 'T',
    suppressusereventsandemails: 'F',
    sys_id: '3041584831686224',
    tax_affecting_address_fields_before_recalc: 'citystatezipcountry',
    templatestored: 'T',
    tobeemailed: 'F',
    tobefaxed: 'F',
    tobeprinted: 'F',
    total: '907.64',
    trandate: '4/19/2014',
    tranid: 'PO-G000614',
    transactionnumber: 'PURCHORD144834',
    type: 'purchord',
    unbilledorders: '1515.64',
    updatedropshiporderqty: 'T',
    version: '30',
    voided: 'F',
    weekendpreference: 'ASIS',
    billaddressee: 'Stonecrest Country Club',
    billphone: null,
    billattention: null,
    billaddr1: '12347 ne 52nd loop',
    billaddr2: null,
    billaddr3: null,
    billzip: '34484',
    billcity: 'oxford',
    billstate: 'FL',
    billcountry: 'US',
    shipphone: null,
    shipcity: null,
    shipcountry_insubrecord: 'US',
    shipstate_insubrecord: null,
    shipzip_insubrecord: null,
    shipaddr3: null,
    shipaddressee: null,
    shipaddr2: null,
    shipattention: null,
    shipaddr1: null
  },
  fieldnames: [
    'nsapiPI',
    'nsapiSR',
    'nsapiVF',
    'nsapiFC',
    'nsapiPS',
    'nsapiVI',
    'nsapiVD',
    'nsapiPD',
    'nsapiVL',
    'nsapiRC',
    'nsapiLI',
    'nsapiLC',
    'nsapiCT',
    'nsbrowserenv',
    'wfPI',
    'wfSR',
    'wfVF',
    'wfFC',
    'wfPS',
    '_eml_nkey_',
    '_multibtnstate_',
    'selectedtab',
    'type',
    'id',
    'externalid',
    'whence',
    'customwhence',
    'entryformquerystring',
    '_csrf',
    'rejected',
    'wfinstances',
    'dbstrantype',
    'bulk',
    'createddate',
    'lastmodifieddate',
    'version',
    'voided',
    'linked',
    'linkedrevrecje',
    'linkedclosedperioddiscounts',
    'entityname',
    'trantypepermcheck',
    'ntype',
    'nluser',
    'nlrole',
    'nldept',
    'nlloc',
    'nlsub',
    'baserecordtype',
    'nlapiCC',
    'taxamountoverride',
    'taxamount2override',
    'templatestored',
    'companyid',
    'partnerid',
    'source',
    'synceventfield',
    'originator',
    'website',
    'oldrevenuecommitment',
    'entityfieldname',
    'currencysymbol',
    'exchangerate',
    'isbasecurrency',
    'currencyprecision',
    'edition',
    'tobeprinted',
    'previous_billaddresslist',
    'billaddresslist',
    'billingaddress_text',
    'billingaddress2_set',
    'billingaddress_key',
    'billingaddress_type',
    'billingaddress_defaultvalue',
    'billisresidential',
    'previous_shipaddresslist',
    'shipisresidential',
    'shipstate',
    'shipzip',
    'shipcountry',
    'shipoverride',
    'tax_affecting_address_fields_before_recalc',
    'shippingaddress_text',
    'defaultaddressee',
    'defaultaddrbook',
    'shippingaddress2_set',
    'shippingaddress_key',
    'shippingaddress_type',
    'shippingaddress_defaultvalue',
    'recordcreatedby',
    'recordcreateddate',
    'prevdate',
    'balance',
    'unbilledorders',
    'creditlimit_origtotal',
    'shipdate',
    'weekendpreference',
    'persistedterms',
    'isinstallment',
    'duedays',
    'mindays',
    'datedriven',
    'discdays',
    'discpct',
    'installmentcount',
    'custbody_4599_mx_operation_type',
    'custbody1',
    'custbody_bf_importdocnum',
    'custbody_sps_pochangestatus',
    'nexttranid',
    'initialtranid',
    'total',
    'origtotal2',
    'origtotal',
    'balreadyrefunded',
    'inventorydetailuitype',
    'haslines',
    'expacct',
    'expacctname',
    'specord',
    'orderstatus',
    'status',
    'statusRef',
    'ordrecvd',
    'ordpartrecvd',
    'ordbilled',
    'dropshipso',
    'transhippinggroup',
    'needsshiprecv',
    'needsbill',
    'updatedropshiporderqty',
    'suppressusereventsandemails',
    'bulktype',
    'billaddress',
    'incoterm',
    'custbody_requested_payment_method',
    'custbody_employee_ref',
    'custbody_g2_isfreeshipping',
    'custbody_g2_ispayinadvance',
    'custbody_g2_source',
    'custbody_isexcess',
    'custbody_pricelevel_ref',
    'custbody_tagname',
    'custbody_weborderid',
    'custbody_widgettype_ref',
    'custbody_bf_prepaidpo',
    'custbody_bf_totalquantity2',
    'custbody_wms_total_received_2',
    'custbody_inventorytype',
    'custbody_wipfli_customer_name',
    'custbody_gsv_pocount',
    'custbody_wms_prepayment_credit_applied',
    'custbody_wms_customer_not_found',
    'custbody_sps_acknowledgmentdate',
    'custbody_sps_supplierinvoicetotal',
    'custbody_sps_terms',
    'custbody_sps_scheduleddate',
    'custbody_sps_supplierterms',
    'custbody_sps_note',
    'custbody_sps_acknowledgmenttype',
    'custbody_emailorderreceivedsummary',
    'custbody_bf_importlog',
    'custbody_gift_card_guid',
    'custbody_isclubtrader',
    'custbody_keycloak_id',
    'custbody_po_store_credit_no',
    'custbody_requested_amount',
    'custbody_site_paycode_adj_pct',
    'custbody_site_price_adj_pct',
    'custbody_po_pricing',
    'custbody_wipfli_wpc',
    'custbody_wms_po_number',
    'custbody_paycode_ref_name',
    'custbody_gsv_spc_name',
    'custbody_gsv_spc_pricelevel',
    'custbody_wms_linked_customer',
    'custbody_wms_vendor_payment_date',
    'custbody_swing_actual_ship_rate',
    'custbody_swing_est_ship_rate',
    'custbody_isgiftcertissued',
    'custbody_variance_email_sent',
    'custbody_scrollingmachines',
    'custbody_alert_of_var_email',
    'custbody_var_email_sent_date',
    'custbody_gsv_po_category_field',
    'custbody_wipfli_child_item_compl',
    'custbody_sps_canceldate',
    'custbody_sps_message',
    'trandate',
    'customform',
    'currency',
    'entity',
    'custbody_vendor_name',
    'custbody_facility_ref',
    'createdfrom',
    'custbody_gsvsite_ref',
    'custbody_paycode_ref',
    'tranid',
    'custbody_purchaseordernotes',
    'custbody_wipfli_hot_order',
    'supervisorapproval',
    'custbody5',
    'custbody_wipfli_vendorbalance',
    'custbody_wf_actual_amount',
    'custbody_wipfli_povariance',
    'subsidiary',
    'custbody_wms_prepay_amount',
    'memo',
    'department',
    'class',
    'location',
    'custbody_cp_ponum',
    'custbody_wipfli_wms_notes',
    'availablevendorcredit',
    'transactionnumber',
    'terms',
    'duedate',
    'otherrefnum',
    'employee',
    'custbody_wipfli_customer_phone',
    'custbody_wipfli_customer_email',
    'custbody_gsv_order_email',
    'custbody_po_fitter_name',
    'custbody_wipfli_requested_shipdate',
    'custbody_wipfli_shipping_address',
    'custbody_bf_pototalquantity',
    'custbody_wms_po_total_received',
    'custbody_wms_prepay_invoice',
    'custbody_wipfli_vend_cat',
    'custbody_wms_check_number',
    'custbody_gsv_promo_code',
    'custbody_gsv_total_promo_amount',
    'custbody_4599_sg_import_permit_num',
    'custbody_intercompany',
    'custbody_my_import_declaration_num',
    'custbody19_2',
    'tobeemailed',
    'email',
    'tobefaxed',
    'fax',
    'message',
    'shipmethod',
    'fob',
    'trackingnumbers',
    'linkedtrackingnumbers',
    'returntrackingnumbers',
    'shipto',
    'shipaddresslist',
    'shipaddress',
    'custbody_sps_addressemail',
    'custbody_total_shipping_labels',
    'custbody4',
    'rectype_261_737_maxnkey',
    'billaddressee',
    'billphone',
    'billattention',
    'billaddr1',
    'billaddr2',
    'billaddr3',
    'billzip',
    'billcity',
    'billstate',
    'billcountry',
    'shipphone',
    'shipcity',
    'shipcountry_insubrecord',
    'shipstate_insubrecord',
    'shipzip_insubrecord',
    'shipaddr3',
    'shipaddressee',
    'shipaddr2',
    'shipattention',
    'shipaddr1'
  ],
  lineitems: {
    recmachcustrecord_wms_to_ref: [],
    item: [
      {
        amount: '0.00',
        amounthasbeenset: 'F',
        billvariancestatus: 'NOVARIANCES',
        billvariancestatusallbook: 'F',
        binitem: 'F',
        class: null,
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: '2014 TP MB STS',
        custcol_ava_taxcodemapping: null,
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: '2',
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '15',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in: 'TaylorMade 2014 Tour Preferred MB Iron Set',
        custcol_wipfli_itemvariance: '-552.74',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'T',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: null,
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_29',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '0',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'F',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '52927',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '29',
        linenumber: null,
        lineuniquekey: '3732133',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '52927',
        options: null,
        origlocation: null,
        origquantity: '0',
        printitems: 'F',
        quantity: '0',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '552.74',
        vendorname: null,
        weightinlb: '0'
      },
      {
        amount: '0.00',
        amounthasbeenset: 'F',
        billvariancestatus: 'NOVARIANCES',
        billvariancestatusallbook: 'F',
        binitem: 'F',
        class: null,
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: 'VR PRO COMBO STS',
        custcol_ava_taxcodemapping: null,
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: '2',
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '5',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in: 'Nike Victory Red Pro Combo Iron Set',
        custcol_wipfli_itemvariance: '-190.9',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'T',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: null,
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_30',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '0',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'F',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '36023',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '30',
        linenumber: null,
        lineuniquekey: '3732135',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '36023',
        options: null,
        origlocation: null,
        origquantity: '0',
        printitems: 'F',
        quantity: '0',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '190.90',
        vendorname: null,
        weightinlb: '0'
      },
      {
        amount: '0.00',
        amounthasbeenset: 'F',
        billvariancestatus: 'NOVARIANCES',
        billvariancestatusallbook: 'F',
        binitem: 'F',
        class: null,
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: 'PP NPORT 2 PUT',
        custcol_ava_taxcodemapping: null,
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: null,
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '15',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in:
          'Titleist Scotty Cameron Pro Platinum Newport 2 Putter',
        custcol_wipfli_itemvariance: '-75',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'T',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: null,
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_31',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '0',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'F',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '41748',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '31',
        linenumber: null,
        lineuniquekey: '3732137',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '41748',
        options: null,
        origlocation: null,
        origquantity: '0',
        printitems: 'F',
        quantity: '0',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '75.00',
        vendorname: null,
        weightinlb: '0'
      },
      {
        amount: '0.00',
        amounthasbeenset: 'F',
        billvariancestatus: 'NOVARIANCES',
        billvariancestatusallbook: 'F',
        binitem: 'F',
        class: null,
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: 'AMP FWG',
        custcol_ava_taxcodemapping: null,
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: null,
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '15',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in: 'Cobra AMP Fairway Wood',
        custcol_wipfli_itemvariance: '-26',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'T',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: null,
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_32',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '0',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'F',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '32785',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '32',
        linenumber: null,
        lineuniquekey: '3732140',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '32785',
        options: null,
        origlocation: null,
        origquantity: '0',
        printitems: 'F',
        quantity: '0',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '26.00',
        vendorname: null,
        weightinlb: '0'
      },
      {
        amount: '0.00',
        amounthasbeenset: 'F',
        billvariancestatus: 'NOVARIANCES',
        billvariancestatusallbook: 'F',
        binitem: 'F',
        class: null,
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: 'G2I ANSER PUT',
        custcol_ava_taxcodemapping: null,
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: null,
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '15',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in: 'Ping G2i Anser Putter',
        custcol_wipfli_itemvariance: '-19',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'T',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: null,
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_33',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '0',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'F',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '37604',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '33',
        linenumber: null,
        lineuniquekey: '3732141',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '37604',
        options: null,
        origlocation: null,
        origquantity: '0',
        printitems: 'F',
        quantity: '0',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '19.00',
        vendorname: null,
        weightinlb: '0'
      },
      {
        amount: '0.00',
        amounthasbeenset: 'F',
        billvariancestatus: 'NOVARIANCES',
        billvariancestatusallbook: 'F',
        binitem: 'F',
        class: null,
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: 'VR PRO SATIN WGS',
        custcol_ava_taxcodemapping: null,
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: null,
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '15',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in: 'Nike Victory Red Pro Satin Chrome Wedge',
        custcol_wipfli_itemvariance: '-22',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'T',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: null,
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_34',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '0',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'F',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '36182',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '34',
        linenumber: null,
        lineuniquekey: '3732143',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '36182',
        options: null,
        origlocation: null,
        origquantity: '0',
        printitems: 'F',
        quantity: '0',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '22.00',
        vendorname: null,
        weightinlb: '0'
      },
      {
        amount: '0.00',
        amounthasbeenset: 'F',
        billvariancestatus: 'NOVARIANCES',
        billvariancestatusallbook: 'F',
        binitem: 'F',
        class: null,
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: 'VR PRO SATIN WGS',
        custcol_ava_taxcodemapping: null,
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: null,
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '15',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in: 'Nike Victory Red Pro Satin Chrome Wedge',
        custcol_wipfli_itemvariance: '-22',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'T',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: null,
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_35',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '0',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'F',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '36182',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '35',
        linenumber: null,
        lineuniquekey: '3732144',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '36182',
        options: null,
        origlocation: null,
        origquantity: '0',
        printitems: 'F',
        quantity: '0',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '22.00',
        vendorname: null,
        weightinlb: '0'
      },
      {
        amount: '552.74',
        amounthasbeenset: 'F',
        billvariancestatus: null,
        billvariancestatusallbook: 'F',
        binitem: 'T',
        class: '2',
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: 'D13367065-19',
        custcol_ava_taxcodemapping: 'PC040400',
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: '2',
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '15',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in: 'TaylorMade 2014 Tour Preferred MB Iron Set',
        custcol_wipfli_itemvariance: '-552.74',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'F',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: '2014 TP MB STS',
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_36',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '1',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'T',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '1336706',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '36',
        linenumber: null,
        lineuniquekey: '4087494',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '1336706',
        options: null,
        origlocation: null,
        origquantity: '1',
        printitems: 'F',
        quantity: '1',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '552.74',
        vendorname: null,
        weightinlb: '0'
      },
      {
        amount: '190.90',
        amounthasbeenset: 'F',
        billvariancestatus: null,
        billvariancestatusallbook: 'F',
        binitem: 'T',
        class: '2',
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: 'D13367075-19',
        custcol_ava_taxcodemapping: 'PC040400',
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: '2',
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '5',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in: 'Nike Victory Red Pro Combo Iron Set',
        custcol_wipfli_itemvariance: '-190.9',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'F',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: 'VR PRO COMBO STS',
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_37',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '1',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'T',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '1336707',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '37',
        linenumber: null,
        lineuniquekey: '4087495',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '1336707',
        options: null,
        origlocation: null,
        origquantity: '1',
        printitems: 'F',
        quantity: '1',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '190.90',
        vendorname: null,
        weightinlb: '0'
      },
      {
        amount: '75.00',
        amounthasbeenset: 'F',
        billvariancestatus: null,
        billvariancestatusallbook: 'F',
        binitem: 'T',
        class: '2',
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: 'D13367085-19',
        custcol_ava_taxcodemapping: 'PC040400',
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: null,
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '15',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in:
          'Titleist Scotty Cameron Pro Platinum Newport 2 Putter',
        custcol_wipfli_itemvariance: '-75',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'F',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: 'PP NPORT 2 PUT',
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_38',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '1',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'T',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '1336708',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '38',
        linenumber: null,
        lineuniquekey: '4087496',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '1336708',
        options: null,
        origlocation: null,
        origquantity: '1',
        printitems: 'F',
        quantity: '1',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '75.00',
        vendorname: null,
        weightinlb: '0'
      },
      {
        amount: '26.00',
        amounthasbeenset: 'F',
        billvariancestatus: null,
        billvariancestatusallbook: 'F',
        binitem: 'T',
        class: '2',
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: 'D13367095-19',
        custcol_ava_taxcodemapping: 'PC040400',
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: null,
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '15',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in: 'Cobra AMP Fairway Wood',
        custcol_wipfli_itemvariance: '-26',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'F',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: 'AMP FWG',
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_39',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '1',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'T',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '1336709',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '39',
        linenumber: null,
        lineuniquekey: '4087497',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '1336709',
        options: null,
        origlocation: null,
        origquantity: '1',
        printitems: 'F',
        quantity: '1',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '26.00',
        vendorname: null,
        weightinlb: '0'
      },
      {
        amount: '19.00',
        amounthasbeenset: 'F',
        billvariancestatus: null,
        billvariancestatusallbook: 'F',
        binitem: 'T',
        class: '2',
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: 'D13367105-19',
        custcol_ava_taxcodemapping: 'PC040400',
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: null,
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '15',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in: 'Ping G2i Anser Putter',
        custcol_wipfli_itemvariance: '-19',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'F',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: 'G2I ANSER PUT',
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_40',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '1',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'T',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '1336710',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '40',
        linenumber: null,
        lineuniquekey: '4087498',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '1336710',
        options: null,
        origlocation: null,
        origquantity: '1',
        printitems: 'F',
        quantity: '1',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '19.00',
        vendorname: null,
        weightinlb: '0'
      },
      {
        amount: '22.00',
        amounthasbeenset: 'F',
        billvariancestatus: null,
        billvariancestatusallbook: 'F',
        binitem: 'T',
        class: '2',
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: 'D13367115-19',
        custcol_ava_taxcodemapping: 'PC040400',
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: null,
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '15',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in: 'Nike Victory Red Pro Satin Chrome Wedge',
        custcol_wipfli_itemvariance: '-22',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'F',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: 'VR PRO SATIN WGS',
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_41',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '1',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'T',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '1336711',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '41',
        linenumber: null,
        lineuniquekey: '4087499',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '1336711',
        options: null,
        origlocation: null,
        origquantity: '1',
        printitems: 'F',
        quantity: '1',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '22.00',
        vendorname: null,
        weightinlb: '0'
      },
      {
        amount: '22.00',
        amounthasbeenset: 'F',
        billvariancestatus: null,
        billvariancestatusallbook: 'F',
        binitem: 'T',
        class: '2',
        custcol_ava_incomeaccount: 'Merchandise Sales',
        custcol_ava_item: 'D13367125-19',
        custcol_ava_taxcodemapping: 'PC040400',
        custcol_ava_upccode: null,
        custcol_customernotes: null,
        custcol_expectedqty: '1',
        custcol_g2_club_length: null,
        custcol_g2_club_number: null,
        custcol_g2_club_number_ref: null,
        custcol_g2_club_numirons_ref: null,
        custcol_g2_clubsinironset: null,
        custcol_g2_condition_ref: '15',
        custcol_g2_dexterity: null,
        custcol_g2_dexterity_ref: null,
        custcol_g2_originalexpected: null,
        custcol_gsv_promo_code_line: null,
        custcol_junk_sku_created: null,
        custcol_misc_item_description: null,
        custcol_multi_sku_created: null,
        custcol_pa_club: null,
        custcol_parent_lineuniquekey: null,
        custcol_po_shaft_material_ref: null,
        custcol_pw2_club: null,
        custcol_upc_created: null,
        custcol_w3_club: null,
        custcol_w48_club: null,
        custcol_w50_club: null,
        custcol_w53_club: null,
        custcol_w_club: null,
        custcol_wipfli_club_number_actual: null,
        custcol_wipfli_club_numirons_actual: null,
        custcol_wipfli_club_shaftmatl_actual: null,
        custcol_wipfli_condition_actual: null,
        custcol_wipfli_g2in: 'Nike Victory Red Pro Satin Chrome Wedge',
        custcol_wipfli_itemvariance: '-22',
        custcol_wipfli_offload_child_gen: null,
        custcol_wms_actual_rate: '0',
        custcol_wms_addedoff: null,
        custcol_wms_childitemgenerator: 'F',
        custcol_wms_exception: null,
        custcol_wms_hideinwms: 'F',
        custcol_wms_parent_item_lookup: null,
        custcol_wms_parentitem: 'VR PRO SATIN WGS',
        custcol_wms_print_label_line: null,
        custcol_wms_recvnotes: null,
        custcol_wms_replacedby: null,
        customer: null,
        ddistrib: '1/1/1970',
        discline: null,
        dropshiporderhasbeenshiprecv: 'F',
        dropshipwarningdisplayed: 'F',
        fulfillable: 'T',
        generateaccruals: 'T',
        groupclosed: 'F',
        groupsetup: null,
        id: '293080_42',
        includegroupwrapper: 'F',
        ingroup: null,
        initquantity: '1',
        inventorydetail: null,
        inventorydetailavail: 'F',
        isbillable: 'F',
        isclosed: 'F',
        isdropshiporderline: 'F',
        islinefulfilled: 'F',
        isnoninventory: 'F',
        isnumbered: 'F',
        isopen: 'T',
        isserial: 'F',
        isspecialorderline: 'F',
        item: '1336712',
        itemhandlingcost: null,
        itempacked: 'F',
        itempicked: 'F',
        itemshippingcost: null,
        itemsubtype: null,
        itemtype: 'InvtPart',
        leadtime: '14',
        line: '42',
        linenumber: null,
        lineuniquekey: '4087500',
        linked: 'F',
        linkedordbill: 'F',
        linkedshiprcpt: 'F',
        location: null,
        locationusesbins: null,
        matchbilltoreceipt: 'F',
        matrixtype: null,
        noprint: 'F',
        olditemid: '1336712',
        options: null,
        origlocation: null,
        origquantity: '1',
        printitems: 'F',
        quantity: '1',
        quantitybilled: '0',
        quantityreceived: '0',
        rate: '22.00',
        vendorname: null,
        weightinlb: '0'
      }
    ],
    approvals: [],
    links: [],
    expense: []
  },
  linetypes: {
    recmachcustrecord_wms_to_ref: 'edit',
    item: 'edit',
    approvals: 'list',
    links: 'list',
    expense: 'edit'
  },
  linefields: {
    recmachcustrecord_wms_to_ref: [
      'recordischanged',
      'id',
      'owner',
      'created',
      'version',
      'custrecord_wms_pick_status',
      'custrecord_wms_parent_transfer_bundle',
      'custrecord_wms_to_luk',
      'custrecord_wms_to_ref',
      'custrecord_wms_transfer_line_item',
      'custrecord_wms_transfer_item_description',
      'custrecord_wms_quantity_to_move',
      'custrecord_wms_item_fulfill_ref',
      'custrecord_wms_transfer_item_receipt',
      'custrecord_wms_bundle_line_errors',
      'custrecord_wms_from_location_bin',
      'custrecord_wms_quarantine_inv_transf',
      'custrecord_wms_to_location_line',
      'custrecord_wms_stand_tran_line'
    ],
    item: [
      'custcol_ava_incomeaccount',
      'custcol_ava_item',
      'custcol_ava_taxcodemapping',
      'custcol_ava_upccode',
      'custcol_wms_parent_item_lookup',
      'custcol_wipfli_g2in',
      'custcol_misc_item_description',
      'item',
      'vendorname',
      'olditemid',
      'custcol_wms_childitemgenerator',
      'location',
      'islinefulfilled',
      'origlocation',
      'class',
      'custcol_g2_condition_ref',
      'custcol_g2_dexterity',
      'custcol_po_shaft_material_ref',
      'custcol_expectedqty',
      'inventorydetail',
      'inventorydetailavail',
      'binitem',
      'isserial',
      'isnumbered',
      'locationusesbins',
      'quantity',
      'rate',
      'custcol_wms_recvnotes',
      'custcol_gsv_promo_code_line',
      'amount',
      'amounthasbeenset',
      'custcol_g2_clubsinironset',
      'custcol_g2_club_number',
      'custcol_wms_actual_rate',
      'custcol_wipfli_itemvariance',
      'quantityreceived',
      'quantitybilled',
      'isbillable',
      'isclosed',
      'options',
      'custcol_customernotes',
      'custcol_g2_club_length',
      'custcol_wms_hideinwms',
      'custcol_wms_replacedby',
      'custcol_wms_exception',
      'custcol_g2_club_number_ref',
      'custcol_g2_club_numirons_ref',
      'custcol_g2_dexterity_ref',
      'custcol_wipfli_club_number_actual',
      'custcol_wipfli_club_numirons_actual',
      'custcol_wipfli_club_shaftmatl_actual',
      'custcol_wipfli_condition_actual',
      'custcol_wms_addedoff',
      'custcol_wms_parentitem',
      'custcol_wms_print_label_line',
      'custcol_g2_originalexpected',
      'custcol_w48_club',
      'custcol_w50_club',
      'custcol_w53_club',
      'custcol_w_club',
      'custcol_w3_club',
      'custcol_pw2_club',
      'custcol_pa_club',
      'custcol_junk_sku_created',
      'custcol_multi_sku_created',
      'custcol_upc_created',
      'custcol_parent_lineuniquekey',
      'custcol_wipfli_offload_child_gen',
      'customer',
      'matchbilltoreceipt',
      'generateaccruals',
      'billvariancestatus',
      'billvariancestatusallbook',
      'fulfillable',
      'initquantity',
      'isopen',
      'line',
      'lineuniquekey',
      'linked',
      'linkedshiprcpt',
      'linkedordbill',
      'itempicked',
      'itempacked',
      'discline',
      'printitems',
      'noprint',
      'ingroup',
      'includegroupwrapper',
      'groupclosed',
      'groupsetup',
      'itemtype',
      'itemsubtype',
      'isnoninventory',
      'id',
      'matrixtype',
      'isdropshiporderline',
      'isspecialorderline',
      'origquantity',
      'dropshiporderhasbeenshiprecv',
      'dropshipwarningdisplayed',
      'leadtime',
      'linenumber',
      'ddistrib',
      'weightinlb',
      'itemshippingcost',
      'itemhandlingcost'
    ],
    approvals: ['approvalentity', 'approvalaction', 'approvaltime'],
    links: [
      'id',
      'trandate',
      'linkurl',
      'type',
      'tranid',
      'status',
      'linktype',
      'total'
    ],
    expense: [
      'category',
      'account',
      'amount',
      'memo',
      'department',
      'class',
      'location',
      'customer',
      'isbillable',
      'custcol_numshippinglabels',
      'custcol_po_ref',
      'custcol_wipfli_offload_child_gen',
      'custcol_gsv_promo_code_line',
      'custcol_parent_lineuniquekey',
      'custcol_upc_created',
      'custcol_multi_sku_created',
      'custcol_junk_sku_created',
      'custcol_pa_club',
      'custcol_pw2_club',
      'custcol_w3_club',
      'custcol_w_club',
      'custcol_w53_club',
      'custcol_w50_club',
      'custcol_w48_club',
      'custcol_g2_originalexpected',
      'custcol_wms_price_override',
      'custcol_wms_origg2name',
      'custcol_misc_item_description',
      'custcol_po_loft',
      'custcol_wms_recvnotes',
      'custcol_wms_print_label_line',
      'custcol_wms_parentitem',
      'custcol_wms_addedoff',
      'custcol_wipfli_parentitemjoin',
      'custcol_wipfli_itemvariance',
      'custcol_wipfli_g2in',
      'custcol_wipfli_discount_amount',
      'custcol_wipfli_dexterity_actual',
      'custcol_wipfli_condition_actual',
      'custcol_wipfli_club_shaftmatl_actual',
      'custcol_wipfli_club_numirons_actual',
      'custcol_wipfli_club_number_actual',
      'custcol_po_set_makeup',
      'custcol_po_model',
      'custcol_po_finish',
      'custcol_po_cushin',
      'custcol_po_club_grind',
      'custcol_po_bounce',
      'custcol_g2_dexterity',
      'custcol_g2_brand',
      'custcol_ava_expenseaccount',
      'custcol_ava_assetaccount',
      'custcol_ava_udf2',
      'custcol_ava_udf1',
      'custcol_po_shaftmodel',
      'custcol_po_lie',
      'custcol_po_length',
      'custcol_sps_so_line',
      'custcol_sps_scheduleqty',
      'custcol_sps_unitprice',
      'custcol_sps_itemnote',
      'custcol_sps_itemstatus',
      'custcol_sps_scheduleqty2',
      'custcol_sps_scheduledate2',
      'custcol_sps_itemstatus2',
      'custcol_g2_itemtype',
      'custcol_g2_category',
      'custcol_wms_actual_rate',
      'custcol_w2_club',
      'custcol_w1_club',
      'custcol_uw_club',
      'custcol_po_shaft_material_ref',
      'custcol_gw_club',
      'custcol_g2_dexterity_ref',
      'custcol_g2_club_numirons_ref',
      'custcol_g2_club_number_ref',
      'custcol_dw_club',
      'custcol_aw_club',
      'custcol_7h_club',
      'custcol_6h_club',
      'custcol_5h_club',
      'custcol_4h_club',
      'custcol_3h_club',
      'custcol_wms_exception',
      'custcol_wms_replacedby',
      'custcol_wms_parent_item_lookup',
      'custcol_wms_hideinwms',
      'custcol_wms_childitemgenerator',
      'custcol_po_shaft_material',
      'custcol_sw_club',
      'custcol_pw_club',
      'custcol_lw_club',
      'custcol_gw2_club',
      'custcol_gw1_club',
      'custcol_g2_shaft_flex_ref',
      'custcol_g2_condition_ref',
      'custcol_g2_clubsinironset',
      'custcol_g2_club_number',
      'custcol_g2_club_length',
      'custcol_expectedqty',
      'custcol_employee_ref',
      'custcol_customernotes',
      'custcol_9_club',
      'custcol_8_club',
      'custcol_7_club',
      'custcol_6_club',
      'custcol_5_club',
      'custcol_4_club',
      'custcol_3_club',
      'custcol_2_club',
      'custcol_1_club',
      'categoryexpaccount',
      'numrules',
      'expenseitem',
      'billableenabled',
      'isclosed',
      'line',
      'linked'
    ]
  },
  matrixfields: {},
  currentlineitems: {},
  currentlineitemindexes: {},
  initialized: true,
  operations: [{ operation: 'loadRecord', args: { id: '293080' } }]
}
